services:
  api:
    build: .
    container_name: churn-api
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_PLUGINS_PREINSTALL_DISABLED: "true"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    command: standalone
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "True"
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/project

  ollama:
    image: ollama/ollama:0.35.1
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      OLLAMA_KEEP_ALIVE: "24h"
    volumes:
      - ollama-data:/root/.ollama

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      API_URL: "http://api:8000"
      OLLAMA_URL: "http://ollama:11434"
    depends_on:
      - api
      - ollama

volumes:
  grafana-storage:
  ollama-data: