{
 "title": "Churn API Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Latest Churn Probability",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "   churn_prediction_probability",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(predict_request_latency_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "   sum(rate(predict_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "   Total Predictions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "   sum(predict_requests_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}